// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5555.TestBot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveCANTalon1;
    public static CANTalon driveCANTalon2;
    public static CANTalon driveCANTalon3;
    public static CANTalon driveCANTalon4;
    public static RobotDrive driveRobotDrive41;
    public static CANTalon winchCANTalon5;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveCANTalon1 = new CANTalon(1);
        LiveWindow.addActuator("drive", "CAN Talon 1", driveCANTalon1);
        
        driveCANTalon2 = new CANTalon(2);
        LiveWindow.addActuator("drive", "CAN Talon 2", driveCANTalon2);
        
        driveCANTalon3 = new CANTalon(3);
        LiveWindow.addActuator("drive", "CAN Talon 3", driveCANTalon3);
        
        driveCANTalon4 = new CANTalon(4);
        LiveWindow.addActuator("drive", "CAN Talon 4", driveCANTalon4);
        
        driveRobotDrive41 = new RobotDrive(driveCANTalon2, driveCANTalon3,
              driveCANTalon1, driveCANTalon4);
        
        driveRobotDrive41.setSafetyEnabled(true);
        driveRobotDrive41.setExpiration(0.1);
        driveRobotDrive41.setSensitivity(0.5);
        driveRobotDrive41.setMaxOutput(1.0);

        winchCANTalon5 = new CANTalon(5);
        LiveWindow.addActuator("winch", "CAN Talon 5", winchCANTalon5);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
