// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5505.kms;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.Ultrasonic;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveCANTalon2;
    public static CANTalon driveCANTalon6;
    public static CANTalon driveCANTalon3;
    public static CANTalon driveCANTalon4;
    public static RobotDrive driveRobotDrive41;
    public static CANTalon intakeCANTalon1;
    public static CANTalon winchCANTalon7;
    public static CANTalon winchCANTalon8;
    public static Servo agitatorservo;
    public static SpeedController agitatormotoragitator;
    public static CANTalon shooterCANTalon5;
    public static Servo cameracameraservo;
    public static Ultrasonic subsystem1Ultrasonic1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveCANTalon2 = new CANTalon(2);
        LiveWindow.addActuator("drive", "CAN Talon 2", driveCANTalon2);
        
        driveCANTalon6 = new CANTalon(6);
        LiveWindow.addActuator("drive", "CAN Talon 6", driveCANTalon6);
        
        driveCANTalon3 = new CANTalon(3);
        LiveWindow.addActuator("drive", "CAN Talon 3", driveCANTalon3);
        
        driveCANTalon4 = new CANTalon(4);
        LiveWindow.addActuator("drive", "CAN Talon 4", driveCANTalon4);
        
        driveRobotDrive41 = new RobotDrive(driveCANTalon6, driveCANTalon3,
              driveCANTalon4, driveCANTalon2);
        
        driveRobotDrive41.setSafetyEnabled(true);
        driveRobotDrive41.setExpiration(0.1);
        driveRobotDrive41.setSensitivity(0.5);
        driveRobotDrive41.setMaxOutput(1.0);
        driveRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        driveRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        intakeCANTalon1 = new CANTalon(1);
        LiveWindow.addActuator("intake", "CAN Talon 1", intakeCANTalon1);
        
        winchCANTalon7 = new CANTalon(7);
        LiveWindow.addActuator("winch", "CAN Talon 7", winchCANTalon7);
        
        winchCANTalon8 = new CANTalon(8);
        LiveWindow.addActuator("winch", "CAN Talon 8", winchCANTalon8);
        
        agitatorservo = new Servo(9);
        LiveWindow.addActuator("agitator", "servo", agitatorservo);
        
        agitatormotoragitator = new Talon(0);
        LiveWindow.addActuator("agitator", "motoragitator", (Talon) agitatormotoragitator);
        
        shooterCANTalon5 = new CANTalon(5);
        LiveWindow.addActuator("shooter", "CAN Talon 5", shooterCANTalon5);
        
        cameracameraservo = new Servo(2);
        LiveWindow.addActuator("camera", "cameraservo", cameracameraservo);
        
        subsystem1Ultrasonic1 = new Ultrasonic(0, 1);
        LiveWindow.addSensor("Subsystem 1", "Ultrasonic 1", subsystem1Ultrasonic1);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
