// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5505.Raphael.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc5505.Raphael.Robot;

/**
 *
 */
public class driveForward extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private double m_distance;
    private double m_speed;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    
    private double startDistance;
    private boolean atDistance = false;
    private double forwardDesiredCount;
    private double reverseDesiredCount;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public driveForward(double distance, double speed) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        m_distance = distance;
        m_speed = speed;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drive);
    }
   
	// Called just before this Command runs the first time
    @Override
    protected void initialize() {
        SmartDashboard.putNumber("DriveTest", 0);
    	startDistance = Robot.drive.getEncoderDistance();
    	forwardDesiredCount = startDistance + m_distance;
        SmartDashboard.putNumber("ForwardDesred", forwardDesiredCount);
    	reverseDesiredCount = startDistance - m_distance;
        SmartDashboard.putNumber("m_speed", m_speed);
    	Robot.drive.driveStraight(m_speed);
    	atDistance = false;
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
    	if (m_distance > 0) {
    		if (forwardDesiredCount <= Robot.drive.getEncoderDistance())
    			atDistance = true;
    	} else {
    		if (reverseDesiredCount >= Robot.drive.getEncoderDistance())
    			atDistance = true;
    	}
        return atDistance;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	SmartDashboard.putNumber("DriveTest", 1);
    	Robot.drive.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	SmartDashboard.putNumber("DriveTest", 2);
    	Robot.drive.stop();
    }
}
