// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5505.kms.subsystems;

import org.usfirst.frc5505.kms.RobotMap;
import org.usfirst.frc5505.kms.commands.*;
import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.RobotDrive;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class drive extends Subsystem {
	double reduction= .2;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon cANTalon2 = RobotMap.driveCANTalon2;
    private final CANTalon cANTalon6 = RobotMap.driveCANTalon6;
    private final CANTalon cANTalon3 = RobotMap.driveCANTalon3;
    private final CANTalon cANTalon4 = RobotMap.driveCANTalon4;
    private final RobotDrive robotDrive41 = RobotMap.driveRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new drivestraight());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    public void drivebase (Joystick drivestick){
    	robotDrive41.mecanumDrive_Cartesian(drivestick.getRawAxis(0)*reduction, drivestick.getRawAxis(1)*reduction,-drivestick.getRawAxis(4)*reduction,0);
    }
    
    public void arcadedrive (double moveValue, double rotateValue, boolean SquaredInputs){
    	robotDrive41.arcadeDrive(.5, 0, true);
    }
}

