// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5505.Raphael.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc5505.Raphael.subsystems.*;

/**
 *
 */
public class middleSwitchLeft extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public middleSwitchLeft() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS /// distance was 215
        addSequential(new setPivot(0.5, 0.4));
/*        addParallel(new setElevador(-40000, 1));
        addSequential(new driveForward(18, .75));
        addSequential(new turnRobot(-23, 0.5));
        addSequential(new driveForward(60, .5));
        addSequential(new turnRobot(23, 0.5));
        addSequential(new AutonIntake(2, .4));
*/   
        addParallel(new setElevador(-40000, 1));
        addSequential(new driveForward(10, .75));
        addSequential(new turnRobot(-28, 0.5));
        addSequential(new driveForward(80, .6));
        addSequential(new AutonIntake(2, .35));
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 
    } 
}
